name: 
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  style-checker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by ${{runner.name}}"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ–¥ï¸ The workspace, ${{ github.workspace }}, is now ready to test your code on the runner."

      - name: Install cpplint
        run: sudo pip install cpplint

      - uses: actions/checkout@v3

      - name: Run cpplint
        run: echo "Okkkkk!"
        #run: ./tools/check_style.sh

#  build:
#    runs-on: ubuntu-latest
#    needs: style-checker
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: create build directory
#        run: 